### PR TITLE
Move things to a util file

### PR DESCRIPTION
**Pull request by PubliqPhirm**
Move things to a util file and add a couple new backgrounds.

### CODE REVIEW

**Comment by PubliqPhirm** [comment]
Let me know if there other functions you feel would work well in the utils file.  There seem to be a few one-line functions in generatePanel that I missed.

**Review by chickens2 — COMMENTED** [review]
The use of file as a variable name overwrites some functionality, not a huge deal since it's not being used but might want to change it

**Comment by PubliqPhirm** [comment]
Can you tell me which variable and filename you're looking at? It seems that I keep finding or making more and more bugs, so I've got another bugfix that I want to push before a merge (it seems that the comic doesn't generate properly when it is supposed to have 300x300 panels)

P.S. For some reason, my e-mail program suggested that I use "Sex toys" as my signature, so I'm leaving that in.

Sex toys

**Review by chickens2 — COMMENTED** [review]
I don't think utility functions should use global variables. In general the modification of global variables by other files should be avoided. What I'm thinking of would make sense as utility functions is functions that are only meant to process some data and return a result, or alter a single variable (included as a parameter).

**Comment by chickens2** [comment]
its generateComic.py 270

**Comment by PubliqPhirm** [comment]
Good point.  That’s probably the source of my bugs.  However, from my understanding, global variables are only global to the module they’re called from and not for the whole program (so declaring a global in utilFunctions would only be global to utilFunctions).  That said, we could make a module whose entire purpose is to house global variables (would that be enough to be considered an object at that point?) if we needed to.

The other question I have is: should I move the image processing files out of the utilFunctions file into an imageUtils file or should I just leave them all in utilFunctions?

**Comment by PubliqPhirm** [comment]
I'm not seeing anything unusual on line 270 of generateComic. Did you mean of another file?  Can you copy & paste the offending line(s) of code?  The only globals I'm seeing in utilFunctions are the transform dictionaries (I don't think those are the ones you're concerned about) and the ones in setPanelSizes (which I definitely could get rid of).

**Review by chickens2 — COMMENTED** [review]
In generateComic.py line 369, the seed looks like it will be None if you are not using a text file as the source of the chat log

**Comment by chickens2** [comment]
Yeah looks like I was mistaken, sorry, still looking for it, not familiar
with github pull request review interface, hold on

**Comment by chickens2** [comment]
ok I guess I was looking actually at code you deleted and moved to
utilfunctions.py 48

**Comment by chickens2** [comment]
As for global variables yeah its those two, I'm concerned about both of them

**Comment by PubliqPhirm** [comment]
How would you suggest I deal with the transform_D and undoTransform_D in some way such that they’re not global variables?  getTransform and undoTransformList both rely on them—should I have them passed in as parameters or should I regenerate the dictionaries everytime they’re needed?

**Comment by chickens2** [comment]
I'm not saying they shouldn't be global variables, just that they shouldn't
be referenced in the util function. I would suggest just taking out the
'global's and doing it like

return transform_D,undoTransform_D

and then

transform_D,undoTransform_D = genTransformDict()

**Comment by PubliqPhirm** [comment]
you can return two things at once!?!? That takes care of a ton of reasons why I'd want to use globals. Learning new things every day. I'll look at it more after I've gotten some sleep.

Sex toys

**Comment by PubliqPhirm** [comment]
Can you double-check that:

1. It works on short transcripts?  I had to add a setter function to `generatePanel` so comics with large panels worked
2. The globals are sufficiently removed?
3. I didn't accidentally undo too many of your changes?

**Comment by chickens2** [comment]
seems to work

**Pull request merged**
