### PR TITLE
Add automatic log & line selection 

### PR DESCRIPTION
**Pull request by PubliqPhirm**
Just pick a folder and `log2comic.py` will take care of the rest!

### CODE REVIEW

**Review by chickens2 — CHANGES_REQUESTED** [review]
I don't think this should be default functionality, requesting to put this change behind a config option

**Comment by chickens2** [comment]
(referring to the "Different nicks should no longer share the same pony" change)

**Comment by PubliqPhirm** [comment]
I don't mind putting it behind a confit option, but I do disagree that it is best to keep it off by default is the best decision. Having two people share a pony is funny on occasion, but the effect would grow old if that were the default behavior.

I've also got another chat converter I'm going to drop tomorrow. This one is for Adium XML files (minibug would enjoy that). I may move the chat log converters into a separate project with my next commit.

**Comment by chickens2** [comment]
I agree that people sharing an emote is not a desirable common occurrence,
but to resolve it in this way would cause inconsistent emotes across users
to be a common occurrence, which to me is also not desirable. I think a
better way of handling it would be to manually assign tags to unassigned
users as needed to reduce common emote collisions. Another possibility
might be hue shifting like in fighting games.

**Comment by PubliqPhirm** [comment]
There might be somewhat of a philosophical difference between us, stemming from how I usually keep anon mode on and you keep it off.  Something we could do to reduce pony collisions and keep names a bit more consistent is to check names against the preset alias list every time, rather than only when both characters are in the comic.

**Comment by chickens2** [comment]
I have also thought about that, but eventually, most and then all available
emotes will theoretically be assigned, and a feature to use only unassigned
tags for users without manual tags would itself result in conflicts.

tbh I initially preferred anon mode, I figured there might be privacy
concerns (that's why I added the feature in the first place), but the
feedback I got seemed to largely prefer usernames, so I went with that for
the default and what I use personally. Although both duplicates and
inconsistent tags are still issues either way, just to different degrees.

**Comment by PubliqPhirm** [comment]
It seems that I’m the only pony who strongly prefers anon mode by default.  Perhaps a compromise would be to ensure there are no duplicates when in anon mode (since it really wouldn’t make sense to have two of the same pony talking) but keep the previous behaviour when in normal mode.

That way, each pony in anon mode will mostly have its own personality, but with some users being shuffled occasionally when two users with the same pony are in the same comic.  Normal mode (where it’s the users all communicating with a pony avatar) is much more tolerant of duplicate ponies, since it’s the user (not the ponies) who are really talking.

**Comment by chickens2** [comment]
I'm not sure it makes sense to fold them into the same config option, since
they are distinct bits of functionality and I can imagine someone wanting a
different combination of them. Maybe it would make sense to have something
like alternate preset combinations of config options? At some point I hope
to add a graphical interface, which should make modifying the defaults more
accessible and make the default settings less definitive. In the meantime I
would have no problem if you wanted to include suggested presets as
alternate config files that can be renamed to config.cfg and mention them
in the documentation.

**Comment by PubliqPhirm** [comment]
I think a list of preset configs is probably the correct way, since that’s what I’ve been using more or less for my config file. Some suggested configs be:

• Current defaults
• Anon mode (with collision checking activated)
• Imgur off (both anon and non)
• My fonts

That way, we could have our defaults in the repository and we can remove the main config.cfg from git tracking.  Copying to config.cfg makes a bit more sense than adding yet another command-line option to specify which config file you want.

As an off-the-wall suggestion, what is your opinion on python3?  I’m finding that the chat converters like to choke up on logs with emojis and other non-ASCII characters in them, so I converted them to python3.  I am considering converting the rest of the project to py3 for consistency and perhaps better emoji handling throughout, but I’d want your opinion first.

Finally, dicks.

**Comment by chickens2** [comment]
I do not expect python 3 to resolve the text emoji issue, I believe this to
be an issue with the pillow graphics library. At some point I'm pretty sure
I changed it so stuff never attempts to convert to ascii, to fix the issue
with non ascii characters crashing the program outright.

It should be possible to add python 3 support by checking the version of
the language and conditionally doing things the python 3 way, or doing
things in a way compatible with both. For now I would rather not remove
python 2.7 support, just because that is what I prefer to use personally.
Unless I'm wrong about it resolving the emoji display issue, then it would
be worth it.

**Comment by PubliqPhirm** [comment]
Results of my python3 experiments this far:

• Instead of having all the random accented characters, emojis are simply left blank (presumably if the output font doesn’t support them)
• The only breaking change (that I’ve noticed) that would require version detection is the way you’d import things from urllib
• There are a ton of bugs related to places that expect an int and suddenly have to deal with a floating-point value

Tests I’m going to do before I’d say python3 is ready for final y/n consideration:

• Run a whole bunch of logs through and hopefully find all the places where I need to change / to // to force integer division
• Specify an emoji-positive font and see how they get handled in the output of an emoji-heavy chat

**Comment by PubliqPhirm** [comment]
I have gotten the emojis to work under python 3!!!!!!!!!

The trick is not to use Apple’s Color Emoji font, since PIL doesn’t like it at all.
Instead, I downloaded Symbola and it worked wonderfully.  I can now display beautiful free black & white emoji in the output.

I’ll clean things up and push commits tomorrow when I’m less likely to make sleep-induced errors that break more things.  One note is that I probably won’t have fixed the arrows for speech bubbles when I put these commits out.  I broke those in my quest to plug all the holes where what were ints in python2 have become floats.

In your commits, do you have any plans/ideas on how to clean up the directory structure?  Specifically, the main directory is seeming a bit cluttered, especially with all those .pyc temp files that python likes to make.

**Comment by chickens2** [comment]
nice, I didn't think it would happen with the emojis working. The speech
arrow thing seems like kind of a big deal though, maybe you could resolve
that before the pull request? I like to be actually using the latest
version and I wouldn't be able to if it's broken in visible ways.

Don't see any pyc files in the repository itself, I don't think they've
been getting committed lately. Not sure what could be done about it
otherwise. Files that are not called by the main program could be moved to
new directories. Does python have a way to organize the python files to be
imported into packages? I haven't looked into it but if it's possible that
could be another thing. Tbh it doesn't bother me personally at this point,
since all the files still fit on one screen.

**Comment by PubliqPhirm** [comment]
I have fixed the speech bubble arrows.  I have not been able to test how the tagger handles under python 3, since I never was able to figure out how to use it under python 2.7.  Be sure to test that before accepting the PR as a whole.

I’ve got a couple more clean-up commits coming this evening, then I’ll give an all-clear to test & accept this PR.

**Review by chickens2 — CHANGES_REQUESTED** [review]
There seems to be a bug introduced here where the background is always the same:

http://i.imgur.com/O0GFPon.jpg
http://i.imgur.com/LPv1P05.jpg
http://i.imgur.com/ALQEGbp.jpg

Reproduceability is broken:
http://i.imgur.com/3ElLm2n.jpg
http://i.imgur.com/JKhnyJ8.jpg

Some other really minor issues:

the BeautifulSoup requirement gives an error trying to install it with python 3, I don't remember why this was included in the first place though, I think it can safely be removed from requirements.txt.

config.cfg not in main directory initially

**Comment by PubliqPhirm** [comment]
• I thought I fixed the reproducibility bug: I noticed it earlier and then searched for anywhere in the codebase where random.seed() was called without any parameters and found one in findEmote.py.  I’ll see if it’s still an issue or if I simply hadn’t yet pushed that fix.
• Next commit will fix the stuck background—I suspect some of the data structure changes may have gotten the seed it uses stuck
• BeautifulSoup should be bs4, but that’s not needed for this commit—it’s an XML parser I’m using to deal with my old Adium logs, which will be a separate PR.
• I’ll copy defaults.cfg to config.cfg in the main folder and re-commit it.

**Comment by chickens2** [comment]
In general I think a good strategy for ensuring that random works
predictably is ensuring that random.seed(somevariable) is called before
every invocation of random. That way not only will it be directly
reproducible, but will also be resistant to changes to the code (maybe
something that changes the order different random variables are generated)
causing different output.

**Review by chickens2 — CHANGES_REQUESTED** [review]
Good job resolving the issues, although now it seems to only work with manually specified files but crashes on any text from the clipboard.

I looked into it a little and I'm pretty sure it's a problem with the processLines function in generateComic.py.

**Comment by PubliqPhirm** [comment]
I just needed to add a .readlines() when you’re getting the clipboard input and it worked.

When you’ve got some time, can you look at PR #14?  That’s a log converter that minibug may be interested in and a few other changes that I made before my fixes from last night.

**Comment by chickens2** [comment]
It says there are conflicts and it can't be merged.

**Pull request merged**
